[package]
name = "advent-of-code"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
aho-corasick = "1.1.3"
clap = "4.4.10"
ndarray = "=0.15.2"
ndarray-linalg = { version = "=0.16.0", features = ["openblas-system"] }
pathfinding = "4.11.0"
regex = "1.11.1"
